=encoding utf8

=head1 LICENSE

=head2 Text

The text for the novella I<The Pope Died on Sunday> is original,
and is Copyright by Shlomi Fish, 2001 and
available under the CC-by-sa licence (
L<http://creativecommons.org/licenses/by-sa/3.0/> ), either version 3.0 or at
your option any later version.
